from .dcgan_generator64 import DCGANGenerator64
from .dcgan_generator128 import DCGANGenerator128
from .dcgan_discriminator64 import DCGANDiscriminator64
from .dcgan_discriminator128 import DCGANDiscriminator128
from .dcgan_discriminator import DCGANDiscriminator
from .dcgan_critic import DCGANCritic
from .dcgan_generator import DCGANGenerator
from .dcgan_critic_v2 import DCGANCriticV2
from .dcgan_generator_v2 import DCGANGeneratorV2
