architecture: dc
variable: cross

epochs: 1000
batch_size: 64
learning_rate: 0.0001
beta1: 0.0
beta2: 0.9
dropout_rate: 0.5
feature_scaling: 1

save_model_filename: null
load_model_filename: null

feed_forward_network: null

data_dir: "data/anisotropic_au_structures_train_val_test/"

tensorboard: true

use_cbn: "False"
use_label_projection: "True"
use_embedding_network: "True"
