architecture: dc
target_variable: cross

epochs: 200
batch_size: 128
learning_rate: 0.0001
beta1: 0.0
beta2: 0.9
dropout_rate: 0.5
feature_scaling: 1

save_model_filename: tmp/dcgan_test_drop=0.5.pth.tar
load_model_filename: null

feed_forward_network: delivery/pretrained_cnn_models/last_epoch_effv2_cross_dimer_cylinders_lr00001_drop05.pth.tar

data_dir: "data/dimer_cylinder_train_val_test/"

tensorboard: false

use_cbn: false
use_label_projection: true
use_embedding_network: true
